name: 小狗帽子和永恒泡芙
description: |
  一些我存在的证据，在时光里它们曾部分代表或属于我。
  「干燥剂之死」是数年前的一次自我剖析
  「气球悲歌」是新的零碎东西
avatar: /assets/images/avatar.jpg

sass:
  style: :compressed

navigation:
  - { name: "气球悲歌", url: "/category/balloon/" }
  - { name: "蓝色干燥剂之死", url: "/category/desiccant/" }
  - { name: "照片", url: "/category/photos/" }
  - { name: "关于我", url: "/about" }

footer-links:
  instagram: darkclouds_watch 

exclude: [Gemfile, Gemfile.lock, node_modules, vendor]
